### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by meyfa** [contane/foreman#126]
### Version

0.4.1

### Actual behavior (issue description)

Output when starting the container:

```
node:internal/modules/cjs/loader:1586
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/sodium-native/prebuilds/linux-x64/sodium-native.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at load (/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/app/node_modules/sodium-native/index.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Node.js v20.18.0
```

### Steps to reproduce

On x86-64:

```
docker run --rm contane/foreman
```

### Custom configuration

none

**Comment by meyfa** [comment]
Appears to be caused by: https://github.com/holepunchto/sodium-native/issues/202

**Comment by meyfa** [comment]
Besides fixing this, we should consider adding a "smoke test". After building the image in CI, we could attempt to launch it and assert some expected output.
